name: Archive Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  store:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python dependencies
        run: pip install fusion360-streamer

      - name: Store to Archive.org
        run: fusion360-streamer
        env:
          STORE_TO_ARCHIVE: 1
